name: kockatoos_nova_ai_chatbot
description: "Official Kockatoos Nova Chatbot SDK for Flutter applications."
version: 0.0.1
homepage: https://kockatoos.com
repository: https://github.com/untitled-developers/kockatoos-nova-ai-chatbot


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  http: ^1.2.0 # Or dio for networking
  flutter_markdown_plus: ^1.0.12
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5
  package_info_plus: ^10.2.1
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^5.1.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - lib/assets/fonts/
    - lib/assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700
